### ISSUE TITLE
Issue in python package - different sequences returned same results

### ISSUE THREAD

**Issue by Cyeee** [cran2367/sgt#1] opened 2019-12-02 01:40 UTC
Hi Chitta Ranjan,
Thanks so much for developing this method/package. It is super helpful to me and is driving real business impact on my work. 
One issue I noticed is that in the python package, it gave same results for sequence ['a','b'] and ['e','f']. I assume the results should be different? 
Many thanks again for developing this!
Yi
<img width="773" alt="Screen Shot 2019-12-01 at 8 35 29 PM" src="https://user-images.githubusercontent.com/11463975/69924699-b5fc5500-147a-11ea-9c52-fa6cae984153.png">

**Comment by Cyeee** [comment] 2019-12-02 03:56
I modified the code a bit and it seems this will work.

`        alphabets_in_sequence = np.unique(sequence)
        
        for i, u in enumerate(alphabets_in_sequence):
            index = [p[0] for p in positions].index(u)

            U = np.array(positions[index][1]).ravel()

            for j, v in enumerate(alphabets_in_sequence):
                index = [p[0] for p in positions].index(v)

                V2 = np.array(positions[index][1]).ravel()

                C = [(i,j) for i in U for j in V2 if j > i]
                
                ## yi added
                pos_i = alphabets_list.index(u)
                pos_j = alphabets_list.index(v)

                W0[pos_i,pos_j] = len(C)
                ## yi added end

                cu = np.array([i[0] for i in C]) 
                cv = np.array([i[1] for i in C]) 
                
                ## yi added
                Wk[pos_i,pos_j] = np.sum(np.exp(-kappa * np.abs(cu - cv)))
                ## yi added end`

**Comment by Cyeee** [comment] 2019-12-02 03:56
`alphabets_list = list(alphabets)`

**Comment by gabrielelanaro** [comment] 2019-12-13 13:47
I agree this seems to be incorrect. Basically the indexes of W0 and Wk can change if the alphabet is not entirely in the sequence.

```
alphabets_in_sequence = np.unique(sequence)
for i, u in enumerate(alphabets_in_sequence):
```

**Comment by cran2367** [comment] 2019-12-13 13:55
@Cyeee @gabrielelanaro I am reviewing this. You can expect a resolution in a week. In the meantime, there is an R package on my github repo that you can use.

**Comment by cran2367** [comment] 2019-12-17 21:34
@Cyeee @gabrielelanaro The issue is resolved. Please 
- uninstall your current sgt using `pip uninstall sgt`. 
- Reinstall with `pip install sgt==1.0.0`.
- Run the notebook here: https://github.com/cran2367/sgt/blob/master/python/sgt.ipynb
- If any problem is still there please comment.
- If the problem is resolved, please close the issue.

**Comment by Cyeee** [comment] 2019-12-17 21:54
Thanks for fixing this!

**Comment by Cyeee** [comment] 2019-12-17 21:54
Thanks for fixing it！
Yi

**Closed as completed** 2019-12-17 21:54 UTC
